Repository arduino/setup-protoc, pull requests merged in 2023-05, with the labels that each got.

#55 Add CI workflow to lint TypeScript and JavaScript code
  .eslintrc.yml
  .github/workflows/check-typescript-task.yml
  README.md
  Taskfile.yml
  package-lock.json
  package.json
  tsconfig.eslint.json
  tsconfig.json
Labels: type: enhancement, topic: infrastructure

#69 Package action to release version v1.2.0
  lib/installer.js
  lib/main.js
  node_modules/@actions/core/package.json
  node_modules/@actions/exec/package.json
  node_modules/@actions/io/package.json
  node_modules/@actions/tool-cache/package.json
  node_modules/semver/package.json
  node_modules/tunnel/package.json
  node_modules/typed-rest-client/package.json
  node_modules/underscore/package.json
  node_modules/uuid/package.json
  package-lock.json
  package.json
Labels: type: enhancement, topic: infrastructure

#72 Update to typescript 4.9.5
  lib/installer.js
  lib/main.js
  package-lock.json
  package.json
  src/installer.ts
  src/main.ts
Labels: type: enhancement, topic: infrastructure

#56 Add CI workflow to validate tsconfig files
  .github/workflows/check-tsconfig-task.yml
  README.md
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#76 Change development policy to continuous packaging
  .github/CONTRIBUTING.md
  .github/workflows/check-packaging-ncc-typescript-npm.yml
  README.md
Labels: topic: documentation, type: enhancement, topic: infrastructure

#44 fix #25: Support ARM64 and other platforms
  __tests__/main.test.ts
  lib/installer.js
  src/installer.ts
Labels: type: enhancement, architecture: arm, topic: code

#79 Fix check-packaging-ncc-typescript-task workflow
  .github/workflows/check-packaging-ncc-typescript-task.yml
Labels: type: imperfection

#73 Update to node v16.18.32
  package-lock.json
  package.json
Labels: type: enhancement

#80 Fix workflow's name typo in trigger events
  .github/workflows/check-packaging-ncc-typescript-task.yml
Labels: type: imperfection, topic: code

#82 v2 release note
  README.md
  package-lock.json
  package.json
Labels: topic: documentation, type: enhancement
